import { ShelterDesign, SimulationParams, ClimateDataPoint, MaterialLayer } from '@/lib/physics/types';

/**
 * Generate ANSYS APDL (Mechanical APDL / MAPDL) input script
 * for thermal analysis of the shelter design.
 */
export function generateAPDL(
  design: ShelterDesign,
  params: SimulationParams,
  climate: ClimateDataPoint[],
  latitude: number
): string {
  const lines: string[] = [];
  const add = (s: string) => lines.push(s);

  add('! ================================================================');
  add('! ANSYS APDL Thermal Analysis Script');
  add('! Generated by SIH26 Passive Thermal Shelter Model');
  add(`! Date: ${new Date().toISOString()}`);
  add('! ================================================================');
  add('');
  add('FINISH');
  add('/CLEAR,START');
  add('');

  // Preprocessor
  add('! --- PREPROCESSOR ---');
  add('/PREP7');
  add('');
  add('! Element type: 3D thermal solid');
  add('ET,1,SOLID70');
  add('');

  // Materials
  add('! --- MATERIAL PROPERTIES ---');
  let matId = 1;
  const writeMaterialProps = (layer: MaterialLayer, id: number) => {
    add(`! Material ${id}: ${layer.name}`);
    add(`MP,KXX,${id},${layer.conductivity}    ! Thermal conductivity [W/m·K]`);
    add(`MP,DENS,${id},${layer.density}          ! Density [kg/m³]`);
    add(`MP,C,${id},${layer.specificHeat}         ! Specific heat [J/kg·K]`);
    add(`MP,EMIS,${id},${layer.emissivity}        ! Emissivity`);
    add('');
  };

  add('! Wall materials');
  for (const layer of design.wallAssembly.layers) {
    writeMaterialProps(layer, matId++);
  }
  add('! Roof materials');
  for (const layer of design.roofAssembly.layers) {
    writeMaterialProps(layer, matId++);
  }
  add('! Floor materials');
  for (const layer of design.floorAssembly.layers) {
    writeMaterialProps(layer, matId++);
  }

  // Geometry
  add('! --- GEOMETRY ---');
  const g = design.geometry;
  add(`! Shape: ${g.shape}`);
  add(`! Dimensions: ${g.length}m x ${g.width}m x ${g.height}m`);
  add(`! Volume: ${g.volume.toFixed(2)} m³`);
  add(`! Wall Area: ${g.wallArea.toFixed(2)} m²`);
  add(`! Roof Area: ${g.roofArea.toFixed(2)} m²`);
  add(`! Floor Area: ${g.floorArea.toFixed(2)} m²`);
  add('');

  if (g.shape === 'box' || g.shape === 'a-frame') {
    // Create block geometry with layers
    let wallThickness = 0;
    for (const layer of design.wallAssembly.layers) {
      wallThickness += layer.thickness;
    }
    add(`! Wall total thickness: ${wallThickness.toFixed(4)} m`);
    add(`BLOCK,0,${g.length},0,${g.width},0,${g.height}`);
    add(`! Note: Create separate volumes for each material layer in detailed model`);
  } else if (g.shape === 'cylinder') {
    const radius = Math.sqrt(g.floorArea / Math.PI);
    add(`CYL4,0,0,${radius.toFixed(4)},,,${g.height}`);
  } else if (g.shape === 'dome' || g.shape === 'hemisphere') {
    const radius = Math.sqrt(g.floorArea / Math.PI);
    add(`SPHERE,0,${radius.toFixed(4)}`);
    add('! Cut to hemisphere');
    add(`BLOCK,-${radius * 2},${radius * 2},-${radius * 2},${radius * 2},-${radius * 2},0`);
    add('VSBV,1,2');
  }
  add('');

  // Mesh
  add('! --- MESH ---');
  add('ESIZE,0.1   ! Element size [m]');
  add('VMESH,ALL');
  add('');

  // Boundary conditions
  add('! --- BOUNDARY CONDITIONS ---');
  add('FINISH');
  add('/SOL');
  add('');
  add('! Transient thermal analysis');
  add('ANTYPE,TRANS');
  add(`! Time step: ${params.timeStepSeconds} s`);
  add(`DELTIM,${params.timeStepSeconds},${params.timeStepSeconds / 2},${params.timeStepSeconds * 2}`);
  add('');

  // Initial condition
  add(`! Initial temperature: ${params.initialIndoorTemp} °C`);
  add(`TUNIF,${params.initialIndoorTemp}`);
  add('');

  // Time-varying loads from climate data
  add('! --- THERMAL LOADS ---');
  add('! Convection on exterior surfaces');
  const hExt = 25; // W/m²K exterior convection coefficient
  const hInt = 8;  // W/m²K interior convection coefficient
  add(`! h_ext = ${hExt} W/m²K (exterior), h_int = ${hInt} W/m²K (interior)`);
  add('');

  // Write time-temperature table
  if (climate.length > 0) {
    add('! Ambient temperature function');
    add('*DIM,TAMB,TABLE,' + Math.min(climate.length, 100) + ',1,1,TIME');
    const step = Math.max(1, Math.floor(climate.length / 100));
    for (let i = 0; i < climate.length; i += step) {
      const time = i * params.timeStepSeconds;
      add(`TAMB(${Math.floor(i / step) + 1},0,1) = ${time}`);
      add(`TAMB(${Math.floor(i / step) + 1},1,1) = ${climate[i].temperature}`);
    }
    add('');
    add('! Apply convection BC with time-varying ambient temperature');
    add(`SF,ALL,CONV,${hExt},%TAMB%`);
  } else {
    add(`SF,ALL,CONV,${hExt},${params.initialIndoorTemp}`);
  }
  add('');

  // Solar radiation (simplified as heat flux on roof)
  if (climate.length > 0) {
    const avgGHI = climate.reduce((s, p) => s + p.ghi, 0) / climate.length;
    const absorptivity = design.roofAssembly.layers.length > 0 ? design.roofAssembly.layers[0].solarAbsorptivity : 0.7;
    add(`! Average solar heat flux on roof: ${(avgGHI * absorptivity).toFixed(1)} W/m²`);
    add(`! (Simplified: apply average absorbed solar flux)`);
    add(`SFA,ALL,1,HFLUX,${(avgGHI * absorptivity).toFixed(1)}`);
  }
  add('');

  // Solution
  add('! --- SOLUTION ---');
  add(`TIME,${climate.length * params.timeStepSeconds}   ! Total simulation time [s]`);
  add('OUTRES,ALL,ALL');
  add('SOLVE');
  add('FINISH');
  add('');

  // Post-processing
  add('! --- POST-PROCESSING ---');
  add('/POST1');
  add('SET,LAST');
  add('PLNSOL,TEMP,,0');
  add('');
  add('! Export nodal temperatures');
  add('/POST26');
  add('NSOL,2,1,TEMP,,TEMP_NODE1');
  add('PRVAR,2');
  add('');
  add('FINISH');

  return lines.join('\n');
}

/** Validation result comparing software vs ANSYS results */
export interface ValidationResult {
  timesteps: number[];
  softwareTemp: number[];
  ansysTemp: number[];
  absoluteError: number[];
  percentageError: number[];
  maxAbsoluteError: number;
  avgAbsoluteError: number;
  maxPercentageError: number;
  avgPercentageError: number;
  status: 'pending' | 'pass' | 'fail';
  passThreshold: number; // °C
}

/**
 * Parse ANSYS results from CSV text.
 * Expected format: timestep,temperature (one per line)
 */
export function parseANSYSResults(csvText: string): { timesteps: number[]; temperatures: number[] } {
  const lines = csvText.trim().split(/\r?\n/);
  const timesteps: number[] = [];
  const temperatures: number[] = [];
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#') || trimmed.startsWith('!')) continue;
    const parts = trimmed.split(/[,\s\t]+/);
    if (parts.length >= 2) {
      const t = parseFloat(parts[0]);
      const temp = parseFloat(parts[1]);
      if (!isNaN(t) && !isNaN(temp)) {
        timesteps.push(t);
        temperatures.push(temp);
      }
    }
  }
  
  return { timesteps, temperatures };
}

/**
 * Compare software simulation results with ANSYS results.
 * @param softwareTemp Indoor temperature array from simulation
 * @param softwareTimeHours Time array in hours
 * @param ansysTimesteps ANSYS time values
 * @param ansysTemps ANSYS temperature values
 * @param passThreshold Maximum acceptable absolute error in °C
 */
export function compareResults(
  softwareTemp: number[],
  softwareTimeHours: number[],
  ansysTimesteps: number[],
  ansysTemps: number[],
  passThreshold: number = 3.0
): ValidationResult {
  // Interpolate software results to ANSYS timesteps
  const interpolated: number[] = [];
  for (const t of ansysTimesteps) {
    // Find bracketing indices
    let lo = 0;
    let hi = softwareTimeHours.length - 1;
    for (let i = 0; i < softwareTimeHours.length - 1; i++) {
      if (softwareTimeHours[i] <= t && softwareTimeHours[i + 1] >= t) {
        lo = i;
        hi = i + 1;
        break;
      }
    }
    if (hi === lo) {
      interpolated.push(softwareTemp[lo]);
    } else {
      const frac = (t - softwareTimeHours[lo]) / (softwareTimeHours[hi] - softwareTimeHours[lo]);
      interpolated.push(softwareTemp[lo] + frac * (softwareTemp[hi] - softwareTemp[lo]));
    }
  }

  const absoluteError = ansysTimesteps.map((_, i) => Math.abs(interpolated[i] - ansysTemps[i]));
  const percentageError = ansysTimesteps.map((_, i) => {
    const ref = Math.abs(ansysTemps[i]);
    return ref > 0.01 ? (absoluteError[i] / ref) * 100 : 0;
  });

  const maxAbsoluteError = Math.max(...absoluteError, 0);
  const avgAbsoluteError = absoluteError.length > 0 ? absoluteError.reduce((a, b) => a + b, 0) / absoluteError.length : 0;
  const maxPercentageError = Math.max(...percentageError, 0);
  const avgPercentageError = percentageError.length > 0 ? percentageError.reduce((a, b) => a + b, 0) / percentageError.length : 0;

  return {
    timesteps: ansysTimesteps,
    softwareTemp: interpolated,
    ansysTemp: ansysTemps,
    absoluteError,
    percentageError,
    maxAbsoluteError,
    avgAbsoluteError,
    maxPercentageError,
    avgPercentageError,
    status: maxAbsoluteError <= passThreshold ? 'pass' : 'fail',
    passThreshold,
  };
}
